#ifndef CLANGWRAPPER_GLOBAL_H
#define CLANGWRAPPER_GLOBAL_H

#include <qglobal.h>

#if defined(QTCREATOR_CLANGWRAPPER_LIB)
#  define QTCREATOR_CLANGWRAPPER_EXPORT Q_DECL_EXPORT
#elif  defined(QTCREATOR_CLANGWRAPPER_STATIC_LIB) // Use single files for manual tests
#  define QTCREATOR_CLANGWRAPPER_EXPORT
#else
#  define QTCREATOR_CLANGWRAPPER_EXPORT Q_DECL_IMPORT
#endif

#endif // CLANGWRAPPER_GLOBAL_H
